import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { FormattedMessage, useIntl } from 'react-intl';
import { LanguageSwitch } from '../components/LanguageSwitch';

type Props = {
  locale: string;
  locales: string[];
  setLocale: (locale: string) => void;
};

const Home: NextPage<Props> = ({ locale, locales, setLocale }) => {
  const { formatMessage } = useIntl();
  return (
    <div className={styles.container}>
      <Head>
        <title>{formatMessage({ defaultMessage: 'Create Next App' })}</title>
        <meta
          name="description"
          content={formatMessage({ defaultMessage: 'Generated by create next app' })}
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LanguageSwitch locale={locale} locales={locales} setLocale={setLocale} />

      <main className={styles.main}>
        <h1 className={styles.title}>
          <FormattedMessage
            id="frontpage.title"
            defaultMessage="Welcome to {link}"
            values={{
              link: <a href="https://nextjs.org">Next.js!</a>,
            }}
            description="This is description context."
          />
        </h1>

        <h2>
          <FormattedMessage id="frontpage.subtitle" defaultMessage="This is great" />
        </h2>

        <p className={styles.description}>
          <FormattedMessage
            defaultMessage="Get started by editing {code}"
            values={{
              code: <code className={styles.code}>pages/index.tsx</code>,
            }}
          />
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>
              <FormattedMessage defaultMessage="Documentation" /> &rarr;
            </h2>
            <p>
              <FormattedMessage defaultMessage="Find in-depth information about Next.js features and API." />
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>
              <FormattedMessage defaultMessage="Learn" /> &rarr;
            </h2>
            <p>
              <FormattedMessage defaultMessage="Learn about Next.js in an interactive course with quizzes!" />
            </p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
            <h2>
              <FormattedMessage defaultMessage="Examples" /> &rarr;
            </h2>
            <p>
              <FormattedMessage defaultMessage="Discover and deploy boilerplate example Next.js projects." />
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>
              <FormattedMessage defaultMessage="Deploy" />
              &rarr;
            </h2>
            <p>
              <FormattedMessage defaultMessage="Instantly deploy your Next.js site to a public URL with Vercel." />
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <FormattedMessage
            defaultMessage="Powered by {name}"
            values={{
              name: (
                <span className={styles.logo}>
                  <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
              ),
            }}
          />
        </a>
      </footer>

      <FormattedMessage defaultMessage="Just another again!!! 🫡 …æå“åæœø¨ü" id="just-added-id" />
    </div>
  );
};

export default Home;
