import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { LanguageSwitch } from '../components/LanguageSwitch';
import Intl from '../i18n';

type Props = {
  setLocale: (locale: string) => void;
};

const Home: NextPage<Props> = ({ setLocale }) => (
  <div className={styles.container}>
    <Head>
      <title>{Intl.t.formatMessage({ id: 'frontpage.pageTitle', defaultMessage: 'Create Next App' })}</title>
      <meta
        name="description"
        content={Intl.t.formatMessage({
          id: 'frontpage.pageDescription',
          defaultMessage: 'Generated by create next app',
        })}
      />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <LanguageSwitch setLocale={setLocale} />

    <main className={styles.main}>
      <h1 className={styles.title}>
        {Intl.t.formatMessage(
          { id: 'frontpage.title', defaultMessage: 'Welcome to {link}' },
          {
            link: (
              <a key="link" href="https://nextjs.org">
                Next.js!
              </a>
            ),
          },
        )}
      </h1>

      <h2>{Intl.t.formatMessage({ id: 'frontpage.subtitle', defaultMessage: 'This is great' })}</h2>

      <p className={styles.description}>
        {Intl.t.formatMessage(
          { id: 'frontpage.description', defaultMessage: 'Get started by editing {code}' },
          {
            code: (
              <code key="code" className={styles.code}>
                pages/index.tsx
              </code>
            ),
          },
        )}
      </p>

      <div className={styles.grid}>
        <a href="https://nextjs.org/docs" className={styles.card}>
          <h2>
            {Intl.t.formatMessage({
              id: 'frontpage.documentation.title',
              defaultMessage: 'Documentation',
            })}{' '}
            &rarr;
          </h2>
          <p>
            {Intl.t.formatMessage({
              id: 'frontpage.documentation.description',
              defaultMessage: 'Find in-depth information about Next.js features and API.',
            })}
          </p>
        </a>

        <a href="https://nextjs.org/learn" className={styles.card}>
          <h2>{Intl.t.formatMessage({ id: 'frontpage.learn.title', defaultMessage: 'Learn' })} &rarr;</h2>
          <p>
            {Intl.t.formatMessage({
              id: 'frontpage.learn.description',
              defaultMessage: 'Learn about Next.js in an interactive course with quizzes!',
            })}
          </p>
        </a>

        <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
          <h2>
            {Intl.t.formatMessage({ id: 'frontpage.example.title', defaultMessage: 'Examples' })} &rarr;
          </h2>
          <p>
            {Intl.t.formatMessage({
              id: 'frontpage.example.description',
              defaultMessage: 'Discover and deploy boilerplate example Next.js projects.',
            })}
          </p>
        </a>

        <a
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
        >
          <h2>
            {Intl.t.formatMessage({ id: 'frontpage.deploy.title', defaultMessage: 'Deploy' })}
            &rarr;
          </h2>
          <p>
            {Intl.t.formatMessage({
              id: 'frontpage.deploy.description',
              defaultMessage: 'Instantly deploy your Next.js site to a public URL with Vercel.',
            })}
          </p>
        </a>
      </div>
    </main>

    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        {Intl.t.formatMessage(
          { id: 'frontpage.poweredByNext', defaultMessage: 'Powered by {name}' },
          {
            name: (
              <span key="name" className={styles.logo}>
                <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
              </span>
            ),
          },
        )}
      </a>
    </footer>
  </div>
);

export default Home;
